version: "3.2"
services:
  ghp-maps:
    build:
      context: .
      dockerfile: ./docker/maps/Dockerfile
      args:
        MAP_FILE: europe_germany_berlin.pbf
    image: ghp-maps
    environment:
      JAVA_EXTRA_OPTS: "-Xmx1g -Xms1g -XX:+UseG1GC -XX:MetaspaceSize=100M"
    volumes:
      - ghp-data:/data

  graphhopper:
    build:
      context: .
    image: graphhopper
    expose:
      - 8989
    ports:
      - 8989:8989
    environment:
      JETTY_PORT: 8989
      JAVA_EXTRA_OPTS: "-Xmx1g -Xms1g -XX:+UseG1GC -XX:MetaspaceSize=100M"
      CONFIG_FILE: /graphhopper/config.properties
    volumes:
      - ./docker/maps/config.properties:/graphhopper/config.properties
      - ghp-data:/data
    restart: unless-stopped
    depends_on:
      - ghp-maps
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  ghp-data:

networks:
  default:
